name: 'minic'
dependencies:
  analyzer: '^0.26.1'
  barback: 'any'
  browser: 'any'
  markdown: 'any'
  mustache: 'any'
dev_dependencies:
  test: '^0.12.0'
transformers:
  - minic/transformer/render_instruction_docs
